# Generated by Django 3.1.5 on 2022-03-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serverinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('host', models.CharField(max_length=64)),
                ('port', models.IntegerField()),
                ('user', models.CharField(max_length=64)),
                ('pwd', models.CharField(max_length=64)),
                ('docker_name', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_del', models.IntegerField(default=0)),
            ],
        ),
    ]
